In [ ]:
import numpy as np
import pandas as pd
import os

In [ ]:
!unzip /content/data-science-income-prediction.zip

Archive:  /content/data-science-income-prediction.zip
  inflating: column_desctiptions.csv
  inflating: sample_submission.csv
  inflating: test.csv
  inflating: train.csv

In [ ]:
# read data
data = pd.read_csv("/content/train.csv")

<ipython-input-3-066463bd3948>:2: DtypeWarning: Columns (19) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv("/content/train.csv")

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1300000 entries, 0 to 1299999
Data columns (total 23 columns):
 #   Column                                Non-Null Count    Dtype
---  ------                                --------------    -----
 0   id                                    1300000 non-null  int64
 1   address_role                          10462 non-null    object
 2   zip_code                              1221957 non-null  object
 3   deposit_balance                       43512 non-null    float64
 4   deposit_incoming                      43512 non-null    float64
 5   deposit_outgoing                      43512 non-null    float64
 6   average_loan_24_months                138241 non-null   float64
 7   average_outstanding_balance_6_months  583462 non-null   float64
 8   children                              0 non-null        float64
 9   credit_history_3_years                31145 non-null    float64
 10  credit_history_1_year                 31145 non-null    float64
 11  date_of_birth                         1300000 non-null  object
 12  education                             1300000 non-null  object
 13  employment_time                       449999 non-null   object
 14  employment_industry                   444824 non-null   object
 15  family_status                         620424 non-null   object
 16  gender                                1300000 non-null  object
 17  housing_type                          85814 non-null    object
 18  income_type                           1300000 non-null  object
 19  marital_status                        1 non-null        object
 20  max_outstanding_balance_12_months     646680 non-null   float64
 21  total_debt                            1299998 non-null  float64
 22  primary_income                        1300000 non-null  float64
dtypes: float64(11), int64(1), object(11)
memory usage: 228.1+ MB

## Data Preprocessing

In [ ]:
!pip -q install featurewiz

  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 151.3/151.3 kB 9.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 81.9/81.9 kB 6.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.6/58.6 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.3/13.3 MB 106.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.3/200.3 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 70.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 116.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 69.1/69.1 kB 6.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 385.8/385.8 kB 28.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.5/133.5 kB 11.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.7/59.7 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 kB 5.9 MB/s eta 0:00:00
  Building wheel for feather-format (setup.py) ... done

In [ ]:
from featurewiz import featurewiz

Imported lazytransform v1.18.

Imported featurewiz 0.6.1. Use the following syntax:
    >>> wiz = FeatureWiz(feature_engg = '', nrows=None, transform_target=True,
        		category_encoders="auto", auto_encoders='VAE', ae_options={},
        		add_missing=False, imbalanced=False, verbose=0)
    >>> X_train_selected, y_train = wiz.fit_transform(X_train, y_train)
    >>> X_test_selected = wiz.transform(X_test)
    >>> selected_features = wiz.features

In [ ]:
target = 'primary_income'

In [ ]:
feats = featurewiz(data, target, corr_limit=0.7, verbose=0)
len(feats)

featurewiz has selected 0.7 as the correlation limit. Change this limit to fit your needs...
    Skipping feature engineering since no feature_engg input...
Skipping category encoding since no category encoders specified in input...
    Single_Label Regression problem
    Loaded train data. Shape = (1300000, 23)
    Single_Label Regression problem
No test data filename given...
Classifying features using a random sample of 10000 rows from dataset...
    Single_Label Regression problem
    loading a sequential sample of 10000 rows into pandas for EDA
#######################################################################################
######################## C L A S S I F Y I N G  V A R I A B L E S  ####################
#######################################################################################
        11 variable(s) to be removed since ID or low-information variables
    	variables removed = ['id', 'address_role', 'deposit_balance', 'deposit_incoming', 'deposit_outgoing', 'children', 'credit_history_3_years', 'credit_history_1_year', 'housing_type', 'marital_status', 'date_of_birth']
train data shape before dropping 10 columns = (1300000, 23)
	train data shape after dropping columns = (1300000, 13)
Removing 11 columns from further processing since ID or low information variables
Starting SULOV with 4 features...
    there are no null values in dataset...
    there are no null values in target column...
Completed SULOV. 2 features selected
Time taken for SULOV method = 52 seconds
Finally 9 vars selected after SULOV
Converting all features to numeric before sending to XGBoost...
    there were no mixed data types or object columns that errored. Data is all numeric...
Shape of train data after adding missing values flags = (1300000, 12)
    Completed XGBoost feature selection in 26 seconds
    Alert: No ID variables ['id'] are included in selected features
Alert: Dont forget to add a missing flag to max_outstanding_balance_12_months to create max_outstanding_balance_12_months_Missing_Flag column
Selected 4 important features:
['max_outstanding_balance_12_months', 'family_status', 'income_type', 'education']
Total Time taken for featurewiz selection = 82 seconds
Output contains a list of 4 important features and a train dataframe

2

In [ ]:
data.isnull().sum()

id                                            0
address_role                            1289538
zip_code                                  78043
deposit_balance                         1256488
deposit_incoming                        1256488
deposit_outgoing                        1256488
average_loan_24_months                  1161759
average_outstanding_balance_6_months     716538
children                                1300000
credit_history_3_years                  1268855
credit_history_1_year                   1268855
date_of_birth                                 0
education                                     0
employment_time                          850001
employment_industry                      855176
family_status                            679576
gender                                        0
housing_type                            1214186
income_type                                   0
marital_status                          1299999
max_outstanding_balance_12_months        653320
total_debt                                    2
primary_income                                0
dtype: int64

In [ ]:
data.shape

(1300000, 23)

In [ ]:
data.head(5)

,id,address_role,zip_code,deposit_balance,deposit_incoming,deposit_outgoing,average_loan_24_months,average_outstanding_balance_6_months,children,credit_history_3_years,...,employment_time,employment_industry,family_status,gender,housing_type,income_type,marital_status,max_outstanding_balance_12_months,total_debt,primary_income
0,0,NaN,Unspecified,NaN,NaN,NaN,NaN,780.0,NaN,NaN,...,NaN,NaN,NaN,F,NaN,Retired Pensioner,NaN,9200.0,0.0,30000.0
1,1,NaN,Unspecified,NaN,NaN,NaN,NaN,36017.0,NaN,NaN,...,NaN,NaN,NaN,F,NaN,Salaried Govt,NaN,104754.4,19067.0,59000.0
2,2,NaN,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,M,NaN,Retired Pensioner,NaN,NaN,18781.0,30000.0
3,3,NaN,Unspecified,NaN,NaN,NaN,NaN,8100.0,NaN,NaN,...,More than five years,Other,Married,F,NaN,Employed,NaN,51800.0,0.0,60000.0
4,4,NaN,Unspecified,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,More than five years,Other,Married,F,NaN,Salaried Govt,NaN,NaN,0.0,40000.0

In [ ]:
# SULOV - 'family_status', 'income_type', 'max_outstanding_balance_12_months', 'education'

In [ ]:
df = data[["family_status","income_type", "max_outstanding_balance_12_months", "education", "primary_income"]]

In [ ]:
df["family_status"].isnull().sum()

679576

In [ ]:
df["max_outstanding_balance_12_months"].isnull().sum()

653320

In [ ]:
df["education"].isnull().sum()

0

## ฉะนั้นตอนนี้มี Categorical - Family Status, Max_oustanding_balance_12_months, education

In [ ]:
df["family_status"].fillna("Single", inplace=True)

In [ ]:
df["family_status"].value_counts()

family_status
Single                 835880
Married                412751
Widowed                 28015
Divorced                16420
Living With Partner      6934
Name: count, dtype: int64

In [ ]:
df["max_outstanding_balance_12_months"].fillna(0, inplace=True)

In [ ]:
df.head()

,family_status,income_type,max_outstanding_balance_12_months,education,primary_income
0,Single,Retired Pensioner,9200.0,Unspecified,30000.0
1,Single,Salaried Govt,104754.4,Unspecified,59000.0
2,Single,Retired Pensioner,0.0,Unspecified,30000.0
3,Married,Employed,51800.0,Higher education,60000.0
4,Married,Salaried Govt,0.0,Secondary / secondary special,40000.0

In [ ]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

def one_hot_encode_columns(df, columns_to_encode):
    """
    One-hot encodes specified columns in a pandas DataFrame.

    Args:
        df (pd.DataFrame): The input DataFrame.
        columns_to_encode (list): A list of column names to one-hot encode.

    Returns:
        pd.DataFrame: The DataFrame with one-hot encoded columns.
    """

    encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore') # sparse_output=False for a numpy array, handle_unknown ignores unknown categories.
    encoded_data = encoder.fit_transform(df[columns_to_encode])
    encoded_columns = encoder.get_feature_names_out(columns_to_encode) # get the new column names.
    encoded_df = pd.DataFrame(encoded_data, columns=encoded_columns)

    # Concatenate the encoded columns with the original DataFrame
    df = pd.concat([df.drop(columns_to_encode, axis=1).reset_index(drop=True), encoded_df.reset_index(drop=True)], axis=1)

    return df

In [ ]:
# Specify the columns to one-hot encode
columns_to_encode = ["family_status","income_type", "education"]

# One-hot encode the columns
encoded_df = one_hot_encode_columns(df, columns_to_encode)

# Print the encoded DataFrame
print(encoded_df)

         max_outstanding_balance_12_months  primary_income  \
0                                   9200.0         30000.0
1                                 104754.4         59000.0
2                                      0.0         30000.0
3                                  51800.0         60000.0
4                                      0.0         40000.0
...                                    ...             ...
1299995                            75040.6         70000.0
1299996                                0.0         28000.0
1299997                            19961.8         50000.0
1299998                           312925.8         90000.0
1299999                                0.0         40000.0

         family_status_Divorced  family_status_Living With Partner  \
0                           0.0                                0.0
1                           0.0                                0.0
2                           0.0                                0.0
3                           0.0                                0.0
4                           0.0                                0.0
...                         ...                                ...
1299995                     0.0                                0.0
1299996                     0.0                                0.0
1299997                     0.0                                0.0
1299998                     0.0                                0.0
1299999                     0.0                                0.0

         family_status_Married  family_status_Single  family_status_Widowed  \
0                          0.0                   1.0                    0.0
1                          0.0                   1.0                    0.0
2                          0.0                   1.0                    0.0
3                          1.0                   0.0                    0.0
4                          1.0                   0.0                    0.0
...                        ...                   ...                    ...
1299995                    1.0                   0.0                    0.0
1299996                    1.0                   0.0                    0.0
1299997                    0.0                   1.0                    0.0
1299998                    0.0                   1.0                    0.0
1299999                    1.0                   0.0                    0.0

         income_type_Employed  income_type_Handicapped  \
0                         0.0                      0.0
1                         0.0                      0.0
2                         0.0                      0.0
3                         1.0                      0.0
4                         0.0                      0.0
...                       ...                      ...
1299995                   0.0                      0.0
1299996                   1.0                      0.0
1299997                   0.0                      0.0
1299998                   0.0                      0.0
1299999                   0.0                      0.0

         income_type_Handicapped 2  ...  income_type_Private Sector Employee  \
0                              0.0  ...                                  0.0
1                              0.0  ...                                  0.0
2                              0.0  ...                                  0.0
3                              0.0  ...                                  0.0
4                              0.0  ...                                  0.0
...                            ...  ...                                  ...
1299995                        0.0  ...                                  0.0
1299996                        0.0  ...                                  0.0
1299997                        0.0  ...                                  0.0
1299998                        0.0  ...                                  0.0
1299999                        0.0  ...                                  0.0

         income_type_Retired Pensioner  income_type_Salaried Govt  \
0                                  1.0                        0.0
1                                  0.0                        1.0
2                                  1.0                        0.0
3                                  0.0                        0.0
4                                  0.0                        1.0
...                                ...                        ...
1299995                            0.0                        1.0
1299996                            0.0                        0.0
1299997                            0.0                        1.0
1299998                            1.0                        0.0
1299999                            1.0                        0.0

         income_type_Selfemployed  education_Academic degree  \
0                             0.0                        0.0
1                             0.0                        0.0
2                             0.0                        0.0
3                             0.0                        0.0
4                             0.0                        0.0
...                           ...                        ...
1299995                       0.0                        0.0
1299996                       0.0                        0.0
1299997                       0.0                        0.0
1299998                       0.0                        0.0
1299999                       0.0                        0.0

         education_Higher education  education_Incomplete higher  \
0                               0.0                          0.0
1                               0.0                          0.0
2                               0.0                          0.0
3                               1.0                          0.0
4                               0.0                          0.0
...                             ...                          ...
1299995                         0.0                          0.0
1299996                         1.0                          0.0
1299997                         0.0                          0.0
1299998                         0.0                          0.0
1299999                         0.0                          0.0

         education_Lower secondary  education_Secondary / secondary special  \
0                              0.0                                      0.0
1                              0.0                                      0.0
2                              0.0                                      0.0
3                              0.0                                      0.0
4                              0.0                                      1.0
...                            ...                                      ...
1299995                        0.0                                      1.0
1299996                        0.0                                      0.0
1299997                        0.0                                      1.0
1299998                        0.0                                      0.0
1299999                        0.0                                      1.0

         education_Unspecified
0                          1.0
1                          1.0
2                          1.0
3                          0.0
4                          0.0
...                        ...
1299995                    0.0
1299996                    0.0
1299997                    0.0
1299998                    1.0
1299999                    0.0

[1300000 rows x 22 columns]

In [ ]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

# Apply StandardScaler
scaler = StandardScaler()
encoded_df["max_outstanding_balance_12_months"] = scaler.fit_transform(encoded_df[["max_outstanding_balance_12_months"]])  # Double brackets to keep 2D

In [ ]:
encoded_df.head(5)

,max_outstanding_balance_12_months,primary_income,family_status_Divorced,family_status_Living With Partner,family_status_Married,family_status_Single,family_status_Widowed,income_type_Employed,income_type_Handicapped,income_type_Handicapped 2,...,income_type_Private Sector Employee,income_type_Retired Pensioner,income_type_Salaried Govt,income_type_Selfemployed,education_Academic degree,education_Higher education,education_Incomplete higher,education_Lower secondary,education_Secondary / secondary special,education_Unspecified
0,-0.387371,30000.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.019574,59000.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,-0.522832,30000.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,0.239872,60000.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,-0.522832,40000.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

## AutoGluon

In [ ]:
!pip -q install autogluon

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.4/40.4 kB 3.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.9 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 3.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.0/117.0 kB 9.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 259.5/259.5 kB 17.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 266.2/266.2 kB 23.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 64.1/64.1 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 430.0/430.0 kB 28.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 352.2/352.2 kB 1.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 174.7/174.7 kB 17.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 196.7/196.7 kB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.0/71.0 kB 6.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 324.4/324.4 kB 2.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.5/139.5 kB 12.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 98.7/98.7 MB 22.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.0/84.0 kB 6.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 278.2/278.2 kB 21.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 64.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 85.5/85.5 kB 7.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 815.2/815.2 kB 51.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 410.5/410.5 kB 29.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 67.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.3/79.3 kB 6.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 52.7/52.7 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 115.3/115.3 kB 11.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 66.4/66.4 MB 33.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 14.9/14.9 MB 37.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 315.8/315.8 kB 26.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 79.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 2.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 111.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 90.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 52.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 40.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 18.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 4.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 87.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 806.1/806.1 kB 51.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 3.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 819.3/819.3 kB 52.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.4/13.4 MB 115.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 485.4/485.4 kB 34.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 116.3/116.3 kB 11.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.5/143.5 kB 13.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.7/2.7 MB 86.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.4/84.4 kB 7.5 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 9.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.3/62.3 kB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 108.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 201.4/201.4 kB 16.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.4/8.4 MB 71.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 128.2/128.2 kB 10.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.6/383.6 kB 29.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 194.8/194.8 kB 16.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 231.8/231.8 kB 19.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.0/469.0 kB 36.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 680.1/680.1 kB 43.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.3/135.3 kB 12.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.3/55.3 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 80.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.5/78.5 kB 7.7 MB/s eta 0:00:00
  Building wheel for nvidia-ml-py3 (setup.py) ... done
  Building wheel for antlr4-python3-runtime (setup.py) ... done
  Building wheel for seqeval (setup.py) ... done
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
textblob 0.19.0 requires nltk>=3.9, but you have nltk 3.8.1 which is incompatible.

In [ ]:
import pandas as pd
from autogluon.tabular import TabularPredictor

In [ ]:
import pandas as pd
from autogluon.tabular import TabularPredictor

from sklearn.preprocessing import StandardScaler

def preprocess_stock_data(train_data):
    # Specify the target column
    target = 'primary_income'

    # Initialize the TabularPredictor with time_limit
    predictor = TabularPredictor(label=target, eval_metric='mean_absolute_percentage_error').fit(train_data, time_limit=300)

    return predictor

In [ ]:
# Predict stock prices
predictor = preprocess_stock_data(encoded_df)

No path specified. Models will be saved in: "AutogluonModels/ag-20250309_012612"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.2
Python Version:     3.11.11
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
CPU Count:          8
Memory Avail:       48.05 GB / 50.99 GB (94.2%)
Disk Space Avail:   194.86 GB / 235.68 GB (82.7%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='experimental' : New in v1.2: Pre-trained foundation model + parallel fits. The absolute best accuracy without consideration for inference speed. Does not support GPU.
	presets='best'         : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'         : Strong accuracy with fast inference speed.
	presets='good'         : Good accuracy with very fast inference speed.
	presets='medium'       : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 300s
AutoGluon will save models to "/content/AutogluonModels/ag-20250309_012612"
Train Data Rows:    1300000
Train Data Columns: 21
Label Column:       primary_income
AutoGluon infers your prediction problem is: 'regression' (because dtype of label-column == float and many unique label-values observed).
	Label info (max, min, mean, stddev): (200000.0, 0.0, 57715.11587, 33358.2076)
	If 'regression' is not the correct problem_type, please manually specify the problem_type parameter during Predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression', 'quantile'])
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    49174.04 MB
	Train Data (Original)  Memory Usage: 208.28 MB (0.4% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 20 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 21 | ['max_outstanding_balance_12_months', 'family_status_Divorced', 'family_status_Living With Partner', 'family_status_Married', 'family_status_Single', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     :  1 | ['max_outstanding_balance_12_months']
		('int', ['bool']) : 20 | ['family_status_Divorced', 'family_status_Living With Partner', 'family_status_Married', 'family_status_Single', 'family_status_Widowed', ...]
	3.2s = Fit runtime
	21 features in original data used to generate 21 features in processed data.
	Train Data (Processed) Memory Usage: 34.71 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 3.62s ...
AutoGluon will gauge predictive performance using evaluation metric: 'mean_absolute_percentage_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.01, Train Rows: 1287000, Val Rows: 13000
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': [{}],
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, {'learning_rate': 0.03, 'num_leaves': 128, 'feature_fraction': 0.9, 'min_data_in_leaf': 3, 'ag_args': {'name_suffix': 'Large', 'priority': 0, 'hyperparameter_tune_kwargs': None}}],
	'CAT': [{}],
	'XGB': [{}],
	'FASTAI': [{}],
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 11 L1 models, fit_strategy="sequential" ...
Fitting model: KNeighborsUnif ... Training model for up to 296.38s of the 296.38s of remaining time.
	-0.5026	 = Validation score   (-mean_absolute_percentage_error)
	1.22s	 = Training   runtime
	38.38s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 256.72s of the 256.72s of remaining time.
	-0.5193	 = Validation score   (-mean_absolute_percentage_error)
	1.13s	 = Training   runtime
	106.83s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 148.72s of the 148.72s of remaining time.
	-0.5427	 = Validation score   (-mean_absolute_percentage_error)
	14.17s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 134.44s of the 134.44s of remaining time.
	-0.5431	 = Validation score   (-mean_absolute_percentage_error)
	6.87s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestMSE ... Training model for up to 127.53s of the 127.53s of remaining time.
	Warning: Reducing model 'n_estimators' from 300 -> 87 due to low time. Expected time usage reduced from 438.7s -> 127.3s...
	-0.5436	 = Validation score   (-mean_absolute_percentage_error)
	106.38s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 20.79s of the 20.79s of remaining time.
	Ran out of time, early stopping on iteration 423.
	-0.543	 = Validation score   (-mean_absolute_percentage_error)
	20.76s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 296.38s of the 0.01s of remaining time.
	Ensemble Weights: {'KNeighborsUnif': 0.8, 'LightGBMXT': 0.16, 'KNeighborsDist': 0.04}
	-0.4984	 = Validation score   (-mean_absolute_percentage_error)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 300.31s ... Best model: WeightedEnsemble_L2 | Estimated inference throughput: 89.5 rows/s (13000 batch size)
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/content/AutogluonModels/ag-20250309_012612")

In [ ]:
test_data = pd.read_csv("/content/test.csv")

In [ ]:
# prompt: preprocess like the train data to test_data

def preprocess_test_data(test_data, predictor):
    # Perform the same preprocessing steps as the training data
    test_data["family_status"].fillna("Single", inplace=True)
    test_data["max_outstanding_balance_12_months"].fillna(0, inplace=True)

    columns_to_encode = ["family_status", "income_type", "education"]
    test_encoded_df = one_hot_encode_columns(test_data[columns_to_encode + ["max_outstanding_balance_12_months"]], columns_to_encode)

    # Ensure the test data has the same columns as the training data after one-hot encoding
    missing_cols = set(encoded_df.columns) - set(test_encoded_df.columns)
    for c in missing_cols:
        test_encoded_df[c] = 0
    test_encoded_df = test_encoded_df[encoded_df.columns]

    # Scale numerical features using the scaler fit on the training data
    test_encoded_df["max_outstanding_balance_12_months"] = scaler.transform(test_encoded_df[["max_outstanding_balance_12_months"]])

    return test_encoded_df

# Preprocess the test data
test_preprocessed = preprocess_test_data(test_data.copy(), predictor)

# Now you can use test_preprocessed for predictions
# Example: predictions = predictor.predict(test_preprocessed)

In [ ]:
test_preprocessed.drop("primary_income", axis=1, inplace=True)

In [ ]:
test_preprocessed.head()

,max_outstanding_balance_12_months,family_status_Divorced,family_status_Living With Partner,family_status_Married,family_status_Single,family_status_Widowed,income_type_Employed,income_type_Handicapped,income_type_Handicapped 2,income_type_Handicapped 3,...,income_type_Private Sector Employee,income_type_Retired Pensioner,income_type_Salaried Govt,income_type_Selfemployed,education_Academic degree,education_Higher education,education_Incomplete higher,education_Lower secondary,education_Secondary / secondary special,education_Unspecified
0,-0.522832,0.0,0.0,0.0,1.0,0.0,0.0,0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,1.521276,0.0,0.0,0.0,1.0,0.0,0.0,0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,-0.066879,0.0,0.0,0.0,1.0,0.0,1.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,-0.522832,0.0,0.0,0.0,1.0,0.0,1.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,4.307423,0.0,0.0,0.0,1.0,0.0,1.0,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [ ]:
from autogluon.tabular import TabularPredictor
from tqdm import tqdm  # For displaying progress bar

def predict_in_batches(predictor, test_data, batch_size=1000):
    """
    Predicts in batches and displays a progress bar.

    Args:
        predictor (TabularPredictor): The trained predictor.
        test_data (pd.DataFrame): The data to predict on.
        batch_size (int): The size of each batch.

    Returns:
        pd.Series: The predictions.
    """
    num_batches = (len(test_data) + batch_size - 1) // batch_size
    predictions = []

    # Use tqdm to display a progress bar
    with tqdm(total=len(test_data), desc="Predicting") as pbar:
        for i in range(num_batches):
            start_idx = i * batch_size
            end_idx = min((i + 1) * batch_size, len(test_data))
            batch_predictions = predictor.predict(test_data.iloc[start_idx:end_idx])
            predictions.extend(batch_predictions)
            pbar.update(end_idx - start_idx)  # Update progress bar

    return pd.Series(predictions, index=test_data.index)

# Example usage:
predictions = predict_in_batches(predictor, test_preprocessed)

Predicting: 100%|██████████| 226659/226659 [51:26<00:00, 73.43it/s]

In [ ]:
predictions[0]

40531.63671875

In [ ]:
# prompt: create the dataframe from predictions including the Id and primary_income

import pandas as pd
# Create a DataFrame from predictions
results = pd.DataFrame({'primary_income': predictions})
print(results.head())

   primary_income
0    40531.636719
1    51832.109375
2    56469.187500
3    39554.917969
4    60395.390625

In [ ]:
results.shape

(226659, 1)

In [ ]:
results.to_csv('predictions.csv')

In [ ]:
# prompt: i want to answer as same as sample_submission.csv format

# Assuming you have already executed the code provided and have the 'results' DataFrame
# containing the predictions.

# Create a submission DataFrame with the required format
submission = pd.DataFrame({'id': test_data['id'], 'primary_income': results['primary_income']})

# Save the submission DataFrame to a CSV file
submission.to_csv('datasci_submission.csv', index=False)